{% set name = "qdoas" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UVVIS-BIRA-IASB/qdoas/archive/refs/tags/3.6.0.tar.gz
  sha256: 762bcb03cff1a3e2abd7047fb917d3f8b2e31f48c4c2ef9ddcc2d532e817e0f1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - cmake
    - make  # [not win]
    - pkg-config
  host:
    - boost
    - coda >=2.24.2
    - eigen
    - hdf4
    - hdf5 >=1.14.2
    - libnetcdf
    - qt-main
    - qwt
  run:
    - coda >=2.24.2
    - eigen
    - hdf4
    - hdf5 >=1.14.2
    - libnetcdf
    - qt-main
    - qwt

test:
  commands:
    - doas_cl

about:
  home: https://uv-vis.aeronomie.be/software/QDOAS/
  summary: 'Application to perform DOAS retrievals of trace gases from spectral measurements'
  description: |
    QDOAS is a cross-platform application based on the long experience of BIRA-IASB
    (Royal Belgian Institute for Space Aeronomy) in the development and improvement of algorithms
    for the retrieval of trace gases from UV-Visible spectral measurements (satellite, ground-based,
    mobile or aircraft-based instruments) using the DOAS (Differential Optical Absorption Spectroscopy).
    This software evolves along with the measurement techniques in DOAS. It has been extensively
    validated in different intercomparison campaigns. The friendly user interface, flexibility and the
    robustness of the algorithms largely contribute to QDOAS success in the world.
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: LICENSE
  doc_url: https://uv-vis.aeronomie.be/software/QDOAS/QDOAS_manual.pdf
  dev_url: https://github.com/UVVIS-BIRA-IASB/qdoas

extra:
  recipe-maintainers:
    - svniemeijer
