{% set name = "qdoas-all" %}
{% set version = "3.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UVVIS-BIRA-IASB/qdoas/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9706ce6f21555cfb7c0a6241a76f78291308f3e79287bc0b5b7dfdf7a82d19d1

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - cmake
    - make  # [not win]
    - pkg-config
  host:
    - libboost-headers
    - coda >=2.24.2
    - eigen
    - hdf4
    - hdf5 >=1.14.2
    - libnetcdf
    - libxmlpp
    - libxml2-devel  # [win]
    - glibmm
    - glib
    - qt-main
    - qwt
  run:
    - coda >=2.24.2
    - hdf4
    - hdf5 >=1.14.2
    - libnetcdf
    - qt-main
    - qwt

outputs:
  - name: doas_cl
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - cmake
        - make  # [not win]
        - pkg-config
      host:
        - libboost-headers
        - coda >=2.24.2
        - eigen
        - hdf4
        - hdf5 >=1.14.2
        - libnetcdf
        - libxmlpp
        - glibmm
      run:
        - coda >=2.24.2
        - hdf4
        - hdf5 >=1.14.2
        - libnetcdf
    test:
      commands:
        - doas_cl

  - name: qdoas
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - cmake
        - make  # [not win]
        - pkg-config
      host:
        - libboost-headers
        - coda >=2.24.2
        - eigen
        - hdf4
        - hdf5 >=1.14.2
        - libnetcdf
        - libxmlpp
        - glibmm
        - qt-main
        - qwt
      run:
        - coda >=2.24.2
        - hdf4
        - hdf5 >=1.14.2
        - libnetcdf
        - qt-main
        - qwt
        - doas_cl

about:
  home: https://uv-vis.aeronomie.be/software/QDOAS/
  summary: 'Application to perform DOAS retrievals of trace gases from spectral measurements'
  description: |
    QDOAS is a cross-platform application based on the long experience of BIRA-IASB
    (Royal Belgian Institute for Space Aeronomy) in the development and improvement of algorithms
    for the retrieval of trace gases from UV-Visible spectral measurements (satellite, ground-based,
    mobile or aircraft-based instruments) using the DOAS (Differential Optical Absorption Spectroscopy).
    This software evolves along with the measurement techniques in DOAS. It has been extensively
    validated in different intercomparison campaigns. The friendly user interface, flexibility and the
    robustness of the algorithms largely contribute to QDOAS success in the world.
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: LICENSE
  doc_url: https://uv-vis.aeronomie.be/software/QDOAS/QDOAS_manual.pdf
  dev_url: https://github.com/UVVIS-BIRA-IASB/qdoas

extra:
  recipe-maintainers:
    - jonasv85
    - svniemeijer
    - tdanckaert
